### ISSUE TITLE
BracketHighlighter not match tags

### ISSUE THREAD

**Issue by JuvenRui** [amitsnyderman/sublime-smarty#14]
use Smarty syntax, BracketHighlighter not highlight match HTML tags, but use HTML syntax, highlight match is ok, how to solve?

 thanks.

**Comment by braver** [comment]
The syntax has been updated to extend the HTML syntax correctly. If it doesn't work now, you may need to look into configuring BracketHighlighter. If you need help you can probably get it in their repo or on the sublime text forum.
