### ISSUE TITLE
Break out of quotes when encountering smarty tag.

### ISSUE THREAD

**Issue by patrick-mcdougle** [amitsnyderman/sublime-smarty#20]
Currently if you have a smarty tag inside of an html attribute, the syntax highlighting doesn't work.

`<div class="someclass{if $somevar} anotherclass{/if}">...</div>`

Currently, the `if` tag is the same color as `someclass`.

It would be awesome if it could detect smarty tags within a quoted string.

**Comment by braver** [comment]
The latest version now supports this.
