### ISSUE TITLE
PR to TextMate

### ISSUE THREAD

**Issue by mcdado** [amitsnyderman/sublime-smarty#22]
Hi! Using Smarty myself I found your repo very useful, but using TextMate 2 I wanted to bring your work back to TextMate 2's original bundle, so [I opened a Pull Request](https://github.com/textmate/php-smarty.tmbundle/pull/3) using your updated syntax. I hope you don't mind, in which case I'll close the Pull Request asap.

**Comment by infininight** [comment]
In this vein do you have a license this bundle is available under so pulling changes across is clearer?

**Comment by mcdado** [comment]
Cheers!
