### ISSUE TITLE
Highlighting on end literal

### ISSUE THREAD

**Issue by piercemcgeough** [amitsnyderman/sublime-smarty#25]
When closing a literal tag {/literal} the following text is highlighted incorrectly until it comes to another forward slash

**Comment by dannyharding10** [comment]
@amitsnyderman This has been broken ever since I upgraded to Sublime Text 3 build 3103 (released 9 Feb. 2016).  When I was on Build 3083 this worked fine. It would be awesome if this could be fixed!

**Comment by braver** [comment]
This shouldn't be an issue anymore in recent versions.
