### ISSUE TITLE
ST is not honoring Comments.tmPreferences since build 4180

### ISSUE THREAD

**Issue by frank-bg** [amitsnyderman/sublime-smarty#30]
as the title says, is there a workaround?

do some test using Windows, build 4169 works as expected, upgrading to build 4180 break the functionality

thanks in advance

**Comment by braver** [comment]
Oh I didn't notice that yet. I did notice that 4183 breaks the entire syntax. It needs to be re-engineered a bit, which I already started doing. I'll also have a look at the comments file.

**Comment by braver** [comment]
I've just released 0.2.0, which should address this issue.
