### ISSUE TITLE
Package not loading since updating Sublime

### ISSUE THREAD

**Issue by leeneilson** [amitsnyderman/sublime-smarty#31]
I'm getting the error below. Any help would be greatly appreciated.

Error loading syntax file "Packages/Smarty/Syntaxes/Smarty.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

**Comment by braver** [comment]
I've just released 0.2.0, which should address this issue.

**Comment by leeneilson** [comment]
@braver thank so much for your help, sorry for the slow reply been one of those weeks 😀

**Comment by braver** [comment]
👍🏻

the package is not yet where it needs to be, but somewhat functional at least
