### ISSUE TITLE
Sublime new Error - missing variable

### ISSUE THREAD

**Issue by nikolayganovski1** [amitsnyderman/sublime-smarty#33]
![image](https://github.com/user-attachments/assets/ab2d309c-f1f6-4f83-bdab-8d98bceafec1)
Since a month or two, my Sublime text has a problem reading and coloring .tpl files, it was fine for the previous 5-6 years, but suddenly the bug happened. I did re-install, didn't work.

**Comment by braver** [comment]
The variable you're missing was added to the HTML syntax [years ago](https://github.com/sublimehq/Packages/commit/2d7ce4583b6b205b492bc1185ae36a8539157060). 

If you're on an outdated version of Sublime Text, you should manually install the [0.1.0 release](https://github.com/amitsnyderman/sublime-smarty/releases/tag/0.1.0).

**Comment by nikolayganovski1** [comment]
> The variable you're missing was added to the HTML syntax [years ago](https://github.com/sublimehq/Packages/commit/2d7ce4583b6b205b492bc1185ae36a8539157060).
> 
> If you're on an outdated version of Sublime Text, you should manually install the [0.1.0 release](https://github.com/amitsnyderman/sublime-smarty/releases/tag/0.1.0).

Updated sublime and worked. Thanks.
